name: Build and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make build script executable
        run: chmod +x ./build.sh

      - name: Run build script
        run: ./build.sh

      - name: Upload build directory as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: build

  create_release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: build

      - name: Check if organiz.sh exists
        run: test -f build/organiz.sh

      - name: Create GitHub Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          files: build/organiz.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
